# File generated by Flopy version 3.8.2 on 04/21/2026 at 10:29:23.
BEGIN OPTIONS
END OPTIONS

BEGIN GRIDDATA
  alh
    CONSTANT       2.50000000
  alv
    CONSTANT       2.50000000
  ath1
    CONSTANT       0.25000000
  ath2
    CONSTANT       0.25000000
  atv
    CONSTANT       0.02500000
END GRIDDATA

